### PR TITLE
Add NFData to all data types

### PR DESCRIPTION
**Pull request by gwils**
This is helpful for writing benchmarks that involve these types.

### CODE REVIEW

**Review by toddmohney — APPROVED** [review]
Looks great! 🏆

**Comment by toddmohney** [comment]
@gwils Mind fixing up the Git conflict in the `.cabal` file? Once that's clear I'll merge this in. Thanks!

**Comment by gwils** [comment]
Done!

**Comment by toddmohney** [comment]
@gwils Thanks for all the great contributions!

**Pull request merged**
